image: maven:3.3.9-jdk-8

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .m2/repository

stages:
  - build

docker-build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - mvn clean package -Pprod -DskipTests verify jib:dockerBuild
    - docker push "$CI_REGISTRY_IMAGE"