image: maven:3.3.9-jdk-8

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .m2/repository

stages:
  - release

docker-push:
  stage: release
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - mvn clean verify jib:build -Pprod -DskipTests -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=$CI_REGISTRY_USER  -Djib.to.auth.password=$CI_REGISTRY_PASSWORD -Dmaven.repo.local=$MAVEN_USER_HOME
