version: '2'
services:
  etrade:
    image: registry.gitlab.com/amirmehdi/etrade:master
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger,faker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://etrade-postgresql:5432/eTrade
      - SPRING_DATASOURCE_USERNAME=eTrade
      - SPRING_DATASOURCE_PASSWORD=eTrade2020
      - SPRING_REDIS_HOST=etrade-redis
      - JHIPSTER_SLEEP=0
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=true
      - JHIPSTER_METRICS_LOGS_REPORT_FREQUENCY=60
    ports:
      - '8080:8080'
  etrade-postgresql:
    image: postgres:12.1
    volumes:
      - ~/volumes/jhipster/eTrade/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eTrade
      - POSTGRES_PASSWORD=eTrade2020
    ports:
      - 5432:5432
  etrade-redis:
    image: redis:alpine
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ~/volumes/jhipster/eTrade/redis/:/data

  jhipster-elasticsearch:
    image: jhipster/jhipster-elasticsearch:v4.1.0
    environment:
      - _JAVA_OPTIONS=-Xms128m -Xmx128m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - log-data:/usr/share/elasticsearch/data
  jhipster-logstash:
    image: jhipster/jhipster-logstash:v4.1.0
    environment:
      - _JAVA_OPTIONS=-Xms128m -Xmx128m
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=jhipster-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    ports:
      - 5000:5000
      - 5000:5000/udp
    volumes:
      - /etc/log-conf/:/usr/share/logstash/pipeline/
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    image: jhipster/jhipster-console:v4.1.0
    environment:
      - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    image: jhipster/jhipster-import-dashboards:v4.1.0
    environment:
      - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
    depends_on:
      - jhipster-elasticsearch

  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - /etc/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:v0.20.0
    ports:
      - 9093:9093
    volumes:
      - /etc/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:6.6.2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  log-data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
