version: '2'
services:
  etrade:
    image: etrade
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger,faker
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://etrade-postgresql:5432/eTrade
      - SPRING_DATASOURCE_USERNAME=eTrade
      - SPRING_DATASOURCE_PASSWORD=eTrade2020
      - SPRING_REDIS_HOST=etrade-redis
      - JHIPSTER_SLEEP=30
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=true
      - JHIPSTER_METRICS_LOGS_REPORT_FREQUENCY=60
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
    ports:
      - '8080:8080'
  etrade-postgresql:
    image: postgres:12.1
    volumes:
      - ~/volumes/jhipster/eTrade/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eTrade
      - POSTGRES_PASSWORD=eTrade2020
    ports:
      - 5432:5432
  etrade-redis:
    image: redis:alpine
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ~/volumes/jhipster/eTrade/redis/:/data

  jhipster-elasticsearch:
    image: jhipster/jhipster-elasticsearch:v4.1.0
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - log-data:/usr/share/elasticsearch/data
  jhipster-logstash:
    image: jhipster/jhipster-logstash:v4.1.0
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=jhipster-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    ports:
      - 5000:5000
      - 5000:5000/udp
    volumes:
      - ./log-conf/:/usr/share/logstash/pipeline/
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    image: jhipster/jhipster-console:v4.1.0
    environment:
      - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    image: jhipster/jhipster-import-dashboards:v4.1.0
    environment:
      - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
    depends_on:
      - jhipster-elasticsearch
volumes:
  log-data:
    driver: local
