version: '2'
services:
  etrade-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/eTrade/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eTrade
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
