version: '2'
services:
  etrade-redis:
    image: redis:alpine
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ~/volumes/jhipster/eTrade/redis/:/data
