export const enum State {
  NONE = 'NONE',
  ACTIVE = 'ACTIVE',
  EXECUTED = 'EXECUTED',
  CANCELLED = 'CANCELLED',
  ERROR = 'ERROR',
  HEADLINE = 'HEADLINE',
  PARTIALLY_EXECUTED = 'PARTIALLY_EXECUTED'
}
